spring:
  application:
    name: wise-task-graph
  data:
    mongodb:
      host: ${MONGO_APP_NAME}
      port: ${MONGO_PORT}
      database: ${MONGO_DB}

server:
  port: ${GRAPH_PORT}

grpc:
  port: ${GRAPH_GRPC_PORT}

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
  level:
    ru.leti.wise.task.graph: INFO
    org.springframework.web: INFO

management:
  tracing:
    sampling:
      probability: 1
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  zipkin:
    tracing:
      endpoint: http://${TEMPO_HOST}:${TEMPO_PORT}/api/v2/spans
